"""Structural integrity of the 78-page hand-maintained static site.

The class of regression this prevents
-------------------------------------
Every page here is hand-authored or generated by a small script, there is no
build step, and nothing resolves a link before it ships. The failure mode is
therefore silent: a directory is renamed, a section anchor is renumbered, a page
is folded into another (``/papers`` -> ``/models#evidence``, ``/notes`` ->
``/forecasts#notes``), and the twelve pages that still pointed at the old URL
keep rendering perfectly while linking into a 404. Nobody notices until a reader
does.

``site_contract.py`` and ``site_nav.py`` already guard the site, but they guard
*prose and navigation markup*: ``site_contract`` fails when the literal string
"The seven models support" disappears, which makes a legitimate copy edit look
like a regression and says nothing about whether the page's links work. These
tests are the complement — entirely structural, with no marketing sentence
asserted anywhere, so they survive a rewrite of every paragraph on the site and
still fail the moment a link, an anchor, a canonical URL or a heading level
breaks.

Everything is resolved the way Vercel serves it: ``cleanUrls`` (``/models`` ->
``models/index.html``), ``trailingSlash: false``, and the ``redirects`` table
from ``vercel.json``. A link to a redirect *source* is correct by design; what
has to exist is the redirect's destination.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

# --------------------------------------------------------------- policy

# Pages deliberately absent from sitemap.xml. Empty today: every public page is
# listed, which is the state we want to hold. An entry here is a policy
# decision and must carry the reason it is not a page we want indexed — for
# example a thank-you page, a print-only variant, or a staging draft. Anything
# added without a reason is a bug being papered over.
SITEMAP_EXCLUSIONS: dict[str, str] = {}

# URL schemes and forms that are not repo-relative links and cannot be resolved
# against the filesystem.
EXTERNAL_PREFIXES = (
    "http://", "https://", "//", "mailto:", "tel:", "data:", "javascript:",
)

# Attributes carrying a URL that must resolve. ``srcset``/``action`` are not
# used anywhere on this site; add them here if that changes.
URL_ATTRIBUTES = ("href", "src")

HEADING_TAGS = ("h1", "h2", "h3", "h4", "h5", "h6")


def _is_internal(url: str) -> bool:
    """True for a link that has to resolve to a file in this repo."""
    if not url or url.startswith("#"):
        return False
    return not url.startswith(EXTERNAL_PREFIXES)


def _link_nodes(page):
    """Every (node, attribute, url) triple on a page that names a URL."""
    for node in page.nodes:
        for attribute in URL_ATTRIBUTES:
            url = node.attrs.get(attribute)
            if url:
                yield node, attribute, url


def _site_absolute(page, url: str) -> str:
    """Turn a page-relative link into a site-absolute one."""
    if url.startswith("/"):
        return url
    base = Path(page.url).parent if page.url != "/" else Path("/")
    path, _, fragment = url.partition("#")
    resolved = (base / path).as_posix() if path else page.url
    # Collapse ./ and ../ without touching the filesystem.
    parts: list[str] = []
    for part in resolved.split("/"):
        if part in ("", "."):
            continue
        if part == "..":
            if parts:
                parts.pop()
            continue
        parts.append(part)
    normalised = "/" + "/".join(parts)
    return f"{normalised}#{fragment}" if fragment else normalised


# --------------------------------------------------------------- 1. links

def test_every_internal_link_resolves(pages, site):
    """No page links to a URL that Vercel cannot serve.

    This is the highest-value check in the suite: dozens of hand-maintained
    cross-links, resolved through the same rules production uses. Every broken
    link is reported at once — fixing them one CI run at a time would take a
    dozen rounds.
    """
    broken: list[str] = []
    for page in pages:
        for node, attribute, url in _link_nodes(page):
            if not _is_internal(url):
                continue
            absolute = _site_absolute(page, url)
            target, _ = site.resolve(absolute)
            if target is None:
                broken.append(
                    f"{page.rel}:{node.line}: <{node.tag} {attribute}=\"{url}\"> "
                    f"— nothing on disk serves {site.canonicalise(site.split(absolute)[0])}"
                )
    assert not broken, (
        f"{len(broken)} internal link(s) do not resolve (cleanUrls + vercel.json "
        "redirects applied):\n  " + "\n  ".join(broken)
    )


def test_every_redirect_destination_resolves(pages, site):
    """A redirect must land somewhere real, including its fragment.

    ``vercel.json`` is the one place a URL can be retired without touching a
    page, so it is also the one place a retirement can rot unnoticed: the
    source keeps 308-ing and the destination quietly stops existing. Six of the
    current fourteen redirects aim at an in-page anchor (``/papers`` ->
    ``/models#evidence``), so the fragment is checked too — landing on the
    right page at the wrong scroll position is still a broken promise.
    """
    config_line: dict[str, int] = {}
    for number, line in enumerate(
        (site.root / "vercel.json").read_text().splitlines(), start=1
    ):
        match = re.search(r'"source":\s*"([^"]+)"', line)
        if match:
            config_line.setdefault(match.group(1), number)

    by_path = {page.path: page for page in pages}
    problems: list[str] = []
    for source, destination in site.redirects.items():
        line = config_line.get(source, 0)
        target, fragment = site.resolve(destination)
        if target is None:
            problems.append(
                f"vercel.json:{line}: redirect {source!r} -> {destination!r} "
                "has no page on disk"
            )
            continue
        page = by_path.get(target)
        if fragment and page is not None and fragment not in page.ids():
            problems.append(
                f"vercel.json:{line}: redirect {source!r} -> {destination!r} "
                f'lands on {page.rel} which has no id="{fragment}"'
            )
    assert not problems, "\n  " + "\n  ".join(problems)


# --------------------------------------------------------------- 2. head

def test_page_declares_required_document_metadata(page):
    """Every page ships the head elements a public URL needs.

    Checked structurally — presence and non-emptiness — never the wording, so a
    retitled page passes and an untitled one fails.
    """
    problems: list[str] = []

    if not re.match(r"\s*<!doctype html>", page.source, re.IGNORECASE):
        problems.append("line 1: missing `<!doctype html>` as the first thing in the file")

    html = next((node for node in page.nodes if node.tag == "html"), None)
    if html is None:
        problems.append("no <html> element")
    elif html.attrs.get("lang") != "en":
        problems.append(
            f'line {html.line}: <html lang="{html.attrs.get("lang", "")}"> — '
            'expected lang="en"'
        )

    metas = page.elements("meta")
    if not any("charset" in node.attrs for node in metas):
        problems.append("no <meta charset>")
    if not any(node.attrs.get("name") == "viewport" for node in metas):
        problems.append('no <meta name="viewport">')

    description = next(
        (node for node in metas if node.attrs.get("name") == "description"), None
    )
    if description is None:
        problems.append('no <meta name="description">')
    elif not description.attrs.get("content", "").strip():
        problems.append(f'line {description.line}: <meta name="description"> is empty')

    title = next((node for node in page.nodes if node.tag == "title"), None)
    if title is None:
        problems.append("no <title>")
    elif not title.visible_text().strip():
        problems.append(f"line {title.line}: <title> is empty")

    assert not problems, f"{page.rel}:\n  " + "\n  ".join(problems)


def test_canonical_url_matches_the_page_location(page, site):
    """``rel=canonical`` must name the URL this file is actually served at.

    A canonical that points anywhere else tells search engines to index a
    different page than the one they fetched. Under ``cleanUrls`` the served
    URL has no ``.html`` extension and no trailing slash, so a canonical
    carrying either is pointing at a URL that 308-redirects.
    """
    canonicals = [
        node
        for node in page.elements("link")
        if "canonical" in node.attrs.get("rel", "").split()
    ]
    assert canonicals, f"{page.rel}: no <link rel=\"canonical\">"
    assert len(canonicals) == 1, (
        f"{page.rel}: {len(canonicals)} canonical links "
        f"(lines {[node.line for node in canonicals]}) — exactly one is allowed"
    )

    href = canonicals[0].attrs.get("href", "")
    expected = site.origin + (page.url if page.url != "/" else "/")
    assert href == expected, (
        f"{page.rel}:{canonicals[0].line}: canonical is {href!r} but this file "
        f"is served at {expected!r}"
    )


# --------------------------------------------------------------- 3. a11y

def _has_accessible_name(node) -> bool:
    return bool(
        node.attrs.get("aria-label", "").strip()
        or node.attrs.get("title", "").strip()
        or node.visible_text().strip()
    )


def test_images_carry_alt_text(page):
    """Every ``<img>`` is either described or explicitly marked decorative.

    ``alt=""`` is the correct WCAG marker for a decorative image, so it is
    accepted — but only where the image genuinely adds nothing: it is
    ``aria-hidden``/``role="presentation"``, or it sits beside text, or its
    enclosing link/button already has an accessible name. An ``alt=""`` image
    that is the sole content of an unlabelled link is a real defect: the link
    then has no name at all in a screen reader. A missing ``alt`` attribute
    always fails — that is an image the author forgot about, not one they
    decided was decorative.
    """
    problems: list[str] = []
    for node in page.elements("img"):
        if "alt" not in node.attrs:
            problems.append(
                f"line {node.line}: <img src=\"{node.attrs.get('src', '')}\"> has "
                "no alt attribute (use alt=\"...\" to describe it, or alt=\"\" "
                "aria-hidden=\"true\" if it is decorative)"
            )
            continue
        if node.attrs["alt"].strip():
            continue
        if node.attrs.get("aria-hidden") == "true":
            continue
        if node.attrs.get("role") in ("presentation", "none"):
            continue
        if node.parent is not None and node.parent.visible_text().strip():
            continue
        if any(
            ancestor.tag in ("a", "button") and _has_accessible_name(ancestor)
            for ancestor in node.ancestors()
        ):
            continue
        problems.append(
            f"line {node.line}: <img src=\"{node.attrs.get('src', '')}\" alt=\"\"> "
            "is empty-alt but nothing else on the page names it — add real alt "
            'text, or aria-hidden="true" if it truly is decorative'
        )
    assert not problems, f"{page.rel}:\n  " + "\n  ".join(problems)


def test_page_has_exactly_one_h1(page):
    """One ``<h1>`` per document: the page's own title in the outline."""
    h1s = page.elements("h1")
    assert len(h1s) == 1, (
        f"{page.rel}: {len(h1s)} <h1> element(s) at lines "
        f"{[node.line for node in h1s]} — a page needs exactly one"
    )


def test_heading_levels_do_not_skip(page):
    """The heading outline descends one level at a time.

    Skipping a level (h2 straight to h4) leaves a hole in the document outline
    that screen-reader users navigate by. Headings are read off the parsed
    tree, so an ``<h4>`` inside a JavaScript template string — ``models/`` has
    one — is correctly ignored.
    """
    headings = [node for node in page.nodes if node.tag in HEADING_TAGS]
    problems: list[str] = []
    previous = None
    for node in headings:
        level = int(node.tag[1])
        if previous is not None and level > previous + 1:
            problems.append(
                f"line {node.line}: <{node.tag}> follows <h{previous}> — "
                f"skips h{previous + 1} "
                f"({node.visible_text().strip()[:60]!r})"
            )
        previous = level
    assert not problems, f"{page.rel}:\n  " + "\n  ".join(problems)


def test_in_page_references_point_at_ids_that_exist(page):
    """Fragments and ARIA relationships must name an id on the same page.

    Covers ``href="#x"``, ``aria-controls``, ``aria-labelledby`` and
    ``aria-describedby``. A dangling ``aria-controls`` silently disables the
    relationship for assistive technology; a dangling ``href="#x"`` is a link
    that goes nowhere. ``site_contract.check_fragment_anchors`` covers the
    cross-page form; this is the same-page half, plus the ARIA attributes it
    does not look at.
    """
    ids = page.ids()
    problems: list[str] = []
    for node in page.nodes:
        for attribute in ("aria-controls", "aria-labelledby", "aria-describedby"):
            value = node.attrs.get(attribute, "")
            for token in value.split():
                if token not in ids:
                    problems.append(
                        f'line {node.line}: <{node.tag} {attribute}="{value}"> — '
                        f'no id="{token}" on this page'
                    )
        href = node.attrs.get("href", "")
        if href.startswith("#") and len(href) > 1 and href[1:] not in ids:
            problems.append(
                f'line {node.line}: <{node.tag} href="{href}"> — '
                f'no id="{href[1:]}" on this page'
            )
    assert not problems, f"{page.rel}:\n  " + "\n  ".join(problems)


def test_links_have_discernible_text(page):
    """Every ``<a>`` announces itself.

    An icon-only link with no ``aria-label`` is read out as its URL, which is
    how the GitHub mark in the site header would sound without the label
    ``site_nav.py`` gives it. Accepts visible text, ``aria-label``, ``title``,
    a described ``<img>``, or an SVG ``<title>``.
    """
    problems: list[str] = []
    for node in page.elements("a"):
        if _has_accessible_name(node):
            continue
        described = any(
            (child.tag == "img" and child.attrs.get("alt", "").strip())
            or (child.tag == "title" and child.visible_text().strip())
            for child in node.descendants()
        )
        if described:
            continue
        problems.append(
            f"line {node.line}: <a href=\"{node.attrs.get('href', '')}\"> has no "
            "text, aria-label, title, or described image"
        )
    assert not problems, f"{page.rel}:\n  " + "\n  ".join(problems)


# --------------------------------------------------------------- 4. sitemap

def _sitemap_paths(site) -> dict[str, int]:
    """Every ``<loc>`` as a site-absolute path, mapped to its line number."""
    text = (site.root / "sitemap.xml").read_text()
    origin = site.origin
    found: dict[str, int] = {}
    for number, line in enumerate(text.splitlines(), start=1):
        for match in re.finditer(r"<loc>([^<]+)</loc>", line):
            location = match.group(1)
            path = location[len(origin):] if location.startswith(origin) else location
            found.setdefault(path or "/", number)
    return found


def test_sitemap_entries_resolve(site):
    """Every advertised URL is a page that exists and is not a redirect.

    A sitemap entry that 404s or 308s is a crawl budget spent on nothing, and
    it is the first thing to rot when a page is renamed.
    """
    problems: list[str] = []
    for path, line in _sitemap_paths(site).items():
        if not path.startswith("/"):
            problems.append(
                f"sitemap.xml:{line}: <loc>{path}</loc> is not on the canonical "
                f"origin {site.origin}"
            )
            continue
        if path in site.redirects:
            problems.append(
                f"sitemap.xml:{line}: {path} is a redirect source in vercel.json "
                f"(-> {site.redirects[path]}), so it can never return 200"
            )
            continue
        target, _ = site.resolve(path)
        if target is None:
            problems.append(f"sitemap.xml:{line}: {path} has no page on disk")
    assert not problems, "\n  " + "\n  ".join(problems)


def test_sitemap_lists_every_public_page(pages, site):
    """No public page is missing from the sitemap.

    The generated release notes are appended to sitemap.xml by
    ``notes/generate_release_notes.py``; a hand-added page has no generator to
    remember it, which is exactly the page that goes unindexed for months.
    """
    listed = set(_sitemap_paths(site))
    missing = [
        f"{page.rel} (served at {page.url})"
        for page in pages
        if page.url not in listed and page.rel not in SITEMAP_EXCLUSIONS
    ]
    assert not missing, (
        f"{len(missing)} public page(s) absent from sitemap.xml — add a <loc>, "
        "or add the page to SITEMAP_EXCLUSIONS at the top of this file with the "
        "reason it must not be indexed:\n  " + "\n  ".join(missing)
    )


# --------------------------------------------------------------- 5. domain

def test_internal_links_do_not_hardcode_the_deployment_domain(pages, site):
    """Internal navigation uses paths, not the current Vercel hostname.

    The canonical domain is expected to change. ``rel=canonical``, ``og:url``
    and ``sitemap.xml`` have to name it; a link from one page of the site to
    another does not, and every one that does is a link that breaks — or worse,
    silently leaves the new domain — on the day the site moves.
    """
    origin = site.origin
    offenders: list[str] = []
    for page in pages:
        for node, attribute, url in _link_nodes(page):
            if not url.startswith(origin):
                continue
            if node.tag == "link" and "canonical" in node.attrs.get("rel", "").split():
                continue
            offenders.append(
                f"{page.rel}:{node.line}: <{node.tag} {attribute}=\"{url}\"> — "
                f"use \"{url[len(origin):] or '/'}\" instead"
            )
    assert not offenders, (
        f"{len(offenders)} internal link(s) hardcode {origin}:\n  "
        + "\n  ".join(offenders)
    )


# --------------------------------------------------------------- 6. sanity

def test_the_suite_actually_found_the_site(pages):
    """Guard against a silently empty run.

    Every other test in this module is parametrised over discovered files. If
    discovery breaks — a path change, a bad exclusion — the whole module would
    pass with zero assertions and look green forever.
    """
    assert len(pages) >= 70, (
        f"only {len(pages)} HTML page(s) discovered; the site has ~78. "
        "Check EXCLUDED_DIRS in tests/conftest.py"
    )


@pytest.mark.parametrize("required", ["vercel.json", "sitemap.xml", "robots.txt"])
def test_deployment_configuration_files_exist(repo_root, required):
    """The three files that define how the site is served must be present."""
    assert (repo_root / required).is_file(), f"{required} is missing from the repo root"


# ------------------------------------------------- 7. shared page behaviour

def test_copy_buttons_have_a_handler_that_will_run(page):
    """A page that renders a copy button must load the script that binds it.

    The handler was pasted verbatim into fourteen pages plus a variant inside
    /connect's own IIFE, and omitted from models/index.html — which renders a
    copy button in #score, the target of fifteen "how to score a reform" links
    from across the site. The button looked live and did nothing. It is one
    delegated listener in reveal.js now, so the failure mode this test guards
    is the reverse: a page that renders the button without loading the file.
    """
    if "data-copy" not in page.source:
        return
    assert "/reveal.js" in page.source, (
        f"{page.rel} renders a [data-copy] button but does not load "
        "/reveal.js, so the button does nothing when clicked"
    )


def test_no_page_rebinds_the_shared_copy_handler(page):
    """Two listeners on one button means two clipboard writes per click.

    Re-pasting the handler into a page is the natural thing to do when adding
    a code block, and nothing about the page would look wrong afterwards.
    """
    assert 'closest("[data-copy]")' not in page.source, (
        f"{page.rel} defines its own [data-copy] click handler; reveal.js "
        "already binds one for every page, and both would fire"
    )
