"""Generate the variable-glossary appendix table from the OBR variables workbook.

Reads data/obr_model_variables_october_2025.xlsx from the model repository and
emits ../sections/glossary_table.tex: a longtable of mnemonic -> definition
(and ONS identifier where published) for every variable referenced in the
equations transcribed in the paper, plus the headline scorecard variables.
"""

from pathlib import Path

import openpyxl

HERE = Path(__file__).parent
XLSX = "/Users/janansadeqian/obr-macroeconomic-model/data/obr_model_variables_october_2025.xlsx"

# Every mnemonic that appears in an equation or table in the paper.
WANTED = sorted(
    set(
        """
GDPM CGG CONS IF DINV VAL X M SDE CDUR RHHDI LFSUR GPW PCE NFWPE R PD
IBUS IBUSX GGI PCIH PCLEB IH IPRL MSGVA CBIUD KMSXH KGAP TCPRO COC KSTAR TAF
HHDI MI FYEMP EMPSC EESC TYWHH NMTRHH SBHH PIRHH PIPHH FSMADJ HHSB HHISC
EECOMPC EECOMPD OSHH FYCPR OS OSGG OSPC RENTCO SA FISIMPS
WFP ADJW PSAVEI EMS ESLFS CGWADJ ERCG ECG LAWADJ ERLA ELA
ETLFS HWA AVH ULFS POP16 PART16 ER ET EPS PRODH EARN PMSGVA CPI
PR PRXMIP PRMIP RPI I7 I9 I4 IROO PRENT DIPHH
XNOG XS XOIL XPS PXNOG PXS PXOIL RPRICE WPG RXD RX PPIY
MNOG MS MOIL MSTFE MGTFE MTFE MC MCGG MIF MDINV MXS MXG PMNOG PMS PMOIL
PMSREL PMGREL SPECX MPS
CGGPS GGFCD CGP CGWS LAWS LAPR RCGIM RLAIM CGIPS LAIPS
INCTAXG TYEM TSEOP TCINV INCTAC CTC NPISHTC CETAX VREC PUBSTIW PUBSTPD
PSCR PSCE PSCB DEP PSGI PSNI PSNB PSNBNSA PSNBCY PSNCR PSND TME
CGNB LANB GGNB PCNB EENIC EMPNIC CT CGT INHT OCT CC
CGSB LASBHH LATSUB CGTSUB
EEES AWEI CPIGR PGDP COMP CB TB WRGTP WFJ ES GAD
""".split()
    )
)


def tex_escape(s):
    return (
        s.replace("\xa0", " ")
        .replace("$", "\\$")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("£", "\\pounds ")
        .replace("^", "\\textasciicircum{}")
        .replace("~", "\\textasciitilde{}")
        .replace("<", "\\textless{}")
        .replace(">", "\\textgreater{}")
    )


def breakable(s):
    """Insert break opportunities after operators in long formula codes."""
    if len(s) > 12:
        for op in "+*/-":
            s = s.replace(op, op + "\\allowbreak ")
    return s


def main():
    wb = openpyxl.load_workbook(XLSX, read_only=True)
    ws = wb.active
    defs = {}
    for row in ws.iter_rows(min_row=7, values_only=True):
        _, desc, code, ons, _, _, _ = (list(row) + [None] * 7)[:7]
        if code and desc:
            defs[str(code).strip()] = (str(desc).strip(), str(ons).strip() if ons else "")

    lines = [
        "% Auto-generated by figures/make_glossary.py -- do not edit by hand.",
        "\\begin{longtable}{@{}p{2.1cm}p{9.6cm}p{2.2cm}@{}}",
        "\\caption{Variable glossary: every mnemonic used in this paper, with the"
        " OBR's published definition and ONS identifier where one exists."
        " The full 636-code glossary is browsable on the model dashboard.}"
        "\\label{tab:glossary}\\\\",
        "\\toprule",
        "Mnemonic & Definition (OBR variable listing) & ONS code \\\\",
        "\\midrule",
        "\\endfirsthead",
        "\\toprule",
        "Mnemonic & Definition & ONS code \\\\",
        "\\midrule",
        "\\endhead",
        "\\bottomrule",
        "\\endfoot",
    ]
    missing = []
    for code in WANTED:
        if code in defs:
            desc, ons = defs[code]
            ons = "" if ons in ("None", "-", "n/a", "N/A") else ons
            lines.append(
                f"\\texttt{{{tex_escape(code)}}} & {tex_escape(desc)} & "
                f"\\texttt{{{breakable(tex_escape(ons))}}} \\\\"
            )
        else:
            missing.append(code)
    lines.append("\\end{longtable}")

    out = HERE.parent / "sections" / "glossary_table.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} with {len(WANTED) - len(missing)} entries")
    if missing:
        print("not in workbook (emulator-internal or reconstructed):", ", ".join(missing))


if __name__ == "__main__":
    main()
