"""Generate the ours-vs-publication comparison figure (fig_comparison.pdf).

Compares this replication's 1-year global FEVD share for UK GDP and UK CPI
against the values published in Brignone & Piffer (2025, BoE Macro Technical
Paper No. 3).

What statistic to compare
-------------------------
The paper's Figure 4 "decomposes the *mean of the sum* of the decomposition
into each identified shock", and its note attributes the gap to 100% to the
unidentified shocks; the text says the six identified shocks explain "around
80%" of the domestic variables, of which global shocks are "around 40%" of
real GDP variation and "50% of CPI variation one year after the shocks".

So the published shares are posterior **means** of shares of **total**
forecast-error variance, renormalised over nothing. This script previously
compared something else: it summed per-shock posterior *medians* and
renormalised them to 100%. Those medians sum to about 0.62 (GDP) and 0.71
(CPI) here, so renormalising inflated every identified share by roughly a
third — which is what closed the CPI gap. It also read the FEVD at column
index 4, and column ``h`` holds the (h+1)-step variance, so "one year" was
five quarters.

Both are fixed via ``analysis.fevd_group_shares`` and
``analysis.fevd_horizon_index`` in the model repo, which form the group share
on each accepted draw. The renormalised sum-of-medians is still written to
the JSON, labelled, because it is what earlier rounds published.

Runs compared
-------------
  - "CI fast config": a FRESH fixed-seed run of the test suite's fast
    configuration (600 NIW posterior draws, sample seed 1, identification
    seed 2, unweighted; identical to tests/conftest.py in the read-only repo
    clone) — recomputed here, not copied. It is a noisy estimator: across
    sampling seeds its global GDP share has a standard deviation of about
    6.5pp, so the distance between it and the production run is mostly Monte
    Carlo, not a systematic disagreement.
  - "Production (weighted)": the repo's production artifact
    (results/summary.md): 10,000 draws, importance-weighted.
  - "Paper (~)": the approximate shares stated in the publication.

Also recomputes the unrestricted oil-price impact response to a world supply
shock (paper: positive, Fig. 2; no numeric IRF values are published or stored
in the repo's validation data, so no IRF overlay is drawn) and writes all
numbers to comparison_numbers.json.

Palette: Okabe-Ito (colorblind-safe), consistent with make_figures.py.
Usage: BOE_VAR_MODEL=~/boe-var-model python make_comparison.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import numpy as np

# Resolvable on any machine. This pointed at one developer's home directory,
# so the figure could not be regenerated by anyone else — which is how a
# superseded statistic stayed in the committed artifact.
REPO = Path(os.environ.get("BOE_VAR_MODEL", Path.home() / "boe-var-model")).expanduser()
if not (REPO / "src" / "boe_var").is_dir():
    raise SystemExit(
        f"boe-var-model checkout not found at {REPO}. "
        "Set BOE_VAR_MODEL to the checkout path."
    )
sys.path.insert(0, str(REPO / "src"))
HERE = os.path.dirname(os.path.abspath(__file__))

import pandas as pd  # noqa: E402

from boe_var import analysis  # noqa: E402
from boe_var.analysis import WORLD_SHOCKS  # noqa: E402
from boe_var.bvar import BVAR  # noqa: E402
from boe_var.data import load_data  # noqa: E402
from boe_var.identification import identify  # noqa: E402

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

plt.rcParams.update({
    "font.size": 8, "axes.titlesize": 8.5, "axes.labelsize": 8,
    "legend.fontsize": 7.5, "xtick.labelsize": 8, "ytick.labelsize": 7,
    "axes.grid": True, "grid.alpha": 0.25, "axes.axisbelow": True,
    "axes.spines.top": False, "axes.spines.right": False,
    "figure.dpi": 150, "savefig.bbox": "tight",
})

# Okabe-Ito, fixed assignment by run identity (never cycled).
C_FAST = "#0072B2"       # blue      - CI fast config (fresh run)
C_PROD = "#E69F00"       # orange    - production weighted artifact
C_PAPER = "#999999"      # grey      - published paper values

I_CPI, I_GDP = 5, 7
QUARTERS_AHEAD = 4       # the paper's "one year after the shocks"

# Fast fixed-seed configuration, identical to tests/conftest.py.
N_DRAWS, SAMPLE_SEED, IDENT_SEED, LAGS = 600, 1, 2, 4

# Production artifact (results/summary.md): 10,000 draws, importance-weighted,
# sample 1992Q1-2025Q1 (2026Q1 vintage). Posterior MEAN of the per-draw group
# share at 4 quarters — the paper-comparable statistic.
PROD = {"gdp": 37.4, "cpi": 42.3}
# The same run under the superseded presentation: sum of per-shock medians,
# renormalised to 100%. Kept so the change is legible, never plotted.
PROD_RENORMALISED = {"gdp": 42.8, "cpi": 49.5}
# Published values (approximate, as stated in the paper).
PAPER = {"gdp": 40.0, "cpi": 50.0}


def main():
    df = load_data()
    df = df.loc[(df.index >= pd.Period("1992Q1", "Q"))
                & (df.index <= pd.Period("2025Q1", "Q"))]
    y = df.to_numpy(dtype=float)
    quarters = pd.period_range("2020Q1", "2021Q2", freq="Q")
    dummies = np.column_stack(
        [(df.index == q).astype(float) for q in quarters])

    model = BVAR(y, lags=LAGS, dummies=dummies, lam=0.2, mu=1.0, theta=1.0)
    draws = model.sample_posterior(N_DRAWS, seed=SAMPLE_SEED)
    accepted = identify(draws, rng=np.random.default_rng(IDENT_SEED),
                        compute_weights=False)
    pairs = [(d, B) for d, B, _ in accepted]
    print(f"fast config: accepted {len(pairs)}/{N_DRAWS}")

    shares = analysis.fevd_group_shares(
        pairs, {"global": WORLD_SHOCKS}, quarters_ahead=QUARTERS_AHEAD)
    g = shares["global"]
    fast = {"gdp": 100.0 * float(g["mean"][I_GDP]),
            "cpi": 100.0 * float(g["mean"][I_CPI])}
    fast_band = {
        var: [100.0 * float(g[k][i]) for k in ("lo68", "hi68")]
        for var, i in (("gdp", I_GDP), ("cpi", I_CPI))
    }
    irf = analysis.irf_bands(pairs, horizons=21)
    oil_impact = float(irf["median"][2, 2, 0])  # oil price, world supply, h=0
    print(f"fast FEVD global shares (mean of per-draw group share): "
          f"GDP {fast['gdp']:.1f}%, CPI {fast['cpi']:.1f}%; "
          f"oil impact {oil_impact:+.2f}")

    # ---- grouped bar chart -------------------------------------------------
    groups = ["UK GDP", "UK CPI"]
    series = [
        (f"Replication, CI fast config ({len(pairs)} accepted / "
         f"{N_DRAWS} draws, unweighted)", C_FAST,
         [fast["gdp"], fast["cpi"]], None),
        ("Replication, production (10,000 draws, weighted)", C_PROD,
         [PROD["gdp"], PROD["cpi"]], None),
        ("Brignone & Piffer (2025), published (approx.)", C_PAPER,
         [PAPER["gdp"], PAPER["cpi"]], "//"),
    ]
    x = np.arange(len(groups))
    w = 0.26
    fig, ax = plt.subplots(figsize=(6.4, 3.0))
    for k, (label, color, vals, hatch) in enumerate(series):
        pos = x + (k - 1) * (w + 0.02)
        bars = ax.bar(pos, vals, width=w, color=color, hatch=hatch,
                      edgecolor="white", linewidth=0.8, label=label)
        for b, v in zip(bars, vals):
            ax.annotate(f"{v:.1f}", (b.get_x() + b.get_width() / 2, v),
                        xytext=(0, 2), textcoords="offset points",
                        ha="center", va="bottom", fontsize=7.5,
                        color="#1a1a2e")
    ax.set_xticks(x)
    ax.set_xticklabels(groups)
    ax.set_ylabel("Global share of 1-yr FEV (%)")
    ax.set_ylim(0, 62)
    ax.axhspan(30, 60, color="#0072B2", alpha=0.06, zorder=0)
    ax.text(0.5, 57.2, "calibration band [30, 60]", fontsize=6.5,
            color="#555555", ha="center")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=1,
              frameon=False)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "fig_comparison.pdf"))
    plt.close(fig)

    out = {
        "statistic": (
            "Posterior mean of the group share formed on each accepted draw, "
            "at the 4-quarter-ahead forecast-error variance, as a share of "
            "TOTAL variance. This is what the paper's Figure 4 plots ('the "
            "mean of the sum of the decomposition') and what its ~40% / ~50% "
            "refer to; the identified shocks leave roughly 20% unexplained, "
            "so the shares are not renormalised."
        ),
        "quarters_ahead": QUARTERS_AHEAD,
        "fast_config": {"n_draws": N_DRAWS, "sample_seed": SAMPLE_SEED,
                        "ident_seed": IDENT_SEED, "accepted": len(pairs),
                        "gdp_global_share_pct": fast["gdp"],
                        "cpi_global_share_pct": fast["cpi"],
                        "gdp_68_band_pct": fast_band["gdp"],
                        "cpi_68_band_pct": fast_band["cpi"],
                        "note": (
                            "A noisy estimator: across sampling seeds the "
                            "global GDP share has a standard deviation of "
                            "about 6.5pp at this draw count. Distance from "
                            "the production run is Monte Carlo, not a "
                            "systematic disagreement."
                        ),
                        "oil_impact_world_supply": oil_impact},
        "production_artifact": PROD,
        "production_artifact_renormalised_superseded": PROD_RENORMALISED,
        "paper": PAPER,
    }
    with open(os.path.join(HERE, "comparison_numbers.json"), "w") as f:
        json.dump(out, f, indent=1)
    print("done")


if __name__ == "__main__":
    main()
